version: '3.8'
services:
    db:
        container_name: 'kw-postgres'
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password123
        expose:
            - '5432'
        restart: always
        image: postgres:latest
    python3-opencv:
        container_name: 'kw-flask-opencv'
        restart: always
        privileged: true
        ports:
            - '5000:5000'
        depends_on:
            - db
        image: codebad/python3-opencv
