version: '3.8'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=kyle
  python3-opencv:
        links:
          - mysql
        privileged: true
        ports:
            - '5000:5000'
        image: codebad/python3-opencv-non-it
